---
- name: Attendre que toutes les VMs soient accessibles via SSH
  hosts: all
  gather_facts: false
  tasks:
    - name: Attendre que la connexion SSH soit prête
      wait_for_connection:
        timeout: 300
        delay: 5
        sleep: 5